name = "xterm" 
license = "GPL-3.0"
licenselink = "https://github.com/manid2/hugo-xterm/blob/main/LICENSE"
description = "Hugo theme for terminal users."
homepage = "https://manid2.github.io/hugo-xterm/"
tags = [
  "blog", 
  "contact",
  "dark", 
  "light",
  "minimal",
  "personal",
  "portfolio",
  "responsive" 
]
features = [
  "blog",
  "clean",
  "minimal",
  "portfolio"
]
min_version = 0.110

[author]
  name = "Mani Kumar"
  homepage = "https://manid2.gitlab.io/"
  twitter = "https://twitter.com/mani_d2"
